In [7]:
assert 2 + 2 == 2 +2, "Its worked"

In [2]:
50 - 5 * 6

20

In [3]:
(50 -5 *6) /4

5.0

In [4]:
8/5

1.6

In [8]:
17 % 3

2

In [1]:
bin(678)
    

'0b1010100110'

In [2]:
"Boston"[-3:]

'ton'

In [3]:
square = [1,2,34,5,5]
square.reverse()
square

[5, 5, 34, 2, 1]

In [11]:
"boston"[3:0:-1]

'tso'

In [14]:
[1,1] in [[1,2],[2,3]]

False

In [16]:
True if 2 != 2 else False

False

In [1]:
# print odd even
oddEven = lambda x: x % 2 == 0 

In [3]:
oddEven(1)

False

In [13]:
def isprime(num):
    for i in range(2,num//2):
        if num % i == 0:
            return False
    return True

In [20]:
list(map(lambda x: x * x, [1,2,3,4]))
    

[1, 4, 9, 16]

In [29]:
from test import isprimetest

In [28]:
isprimetest(5)

True

COVID-DATASET EXERCISE 
country = ['India', 'UK', "India","UK","China","USA","China","China"] deaths = [10, 20, 30,40,1,23,56,1]

Task 1: Make a dict with Key as country value as deaths

Task 2: How many Total deaths have occurred in each country the result should be displayed as a Dict
15 mins solve this.....

Task 3: Find the unique country name in the given list: 
['India', 'UK', "India","UK","china","USA","China","China",”INDIA”,”RUSSIA”,”United Kingdom”]

Basic programs 
-	Can you write a program to find the average of odd numbers in the given list?
-	Write a Python Program to Find the third Largest Number in the given list?
-	Write a Python Program to find the count of Even and odd numbers in the given list? 
-	Write a Python Program to find the sum of all Even and odd numbers in the given list? 
-	Write a Python Program to find the Avg. of numbers which are multiples of 7 in the given list? 
Data= [68, 71, 21, 68, 32, 80, 64, 52, 92, 97, 93, 37, 61, 62, 23, 81, 67, 84, 33, 41, 92, 51, 71, 52, 92, 43, 80, 74, 69, 92, 79, 78, 70, 31, 34, 79, 73, 77, 96, 87, 53, 47, 85, 58, 58, 87, 44, 29, 94, 23, 65, 49, 71, 57, 96, 74, 30, 65, 62, 85, 34, 21, 81, 79, 84, 87, 22, 45, 59, 91, 26, 22, 46, 71, 60, 21, 67, 21, 56, 38, 82, 95, 77, 55, 37,61, 59, 89, 61, 75, 97, 72, 58, 23, 78, 20, 95, 67, 59, 56, 93, 82,35, 78, 94, 67, 25, 95, 90, 80, 78, 73, 91, 52, 59, 96, 46, 94, 99,78, 53, 40, 67, 76, 73, 46, 77, 40, 34, 38, 34, 42, 69, 86, 61, 76,21, 90, 52, 65, 36, 93, 55, 86, 95, 65, 30, 89, 86, 20, 92, 46, 58,75, 43, 57, 53, 42, 43, 37, 26, 90, 58, 31, 73, 71, 63, 70, 72, 78,26, 39, 35, 58, 84, 56, 24, 73, 36, 75, 32, 35, 56, 87, 87, 73, 80,78, 25, 61, 38, 94, 36, 90, 70, 65, 34, 61, 44, 85, 41, 50, 23, 34,20, 87, 84, 30, 21, 84, 65, 85, 88, 73, 54, 47, 77, 41, 35, 71]


In [8]:
country = ['India', 'UK', "India","UK","China","USA","China","China"] 
deaths = [10, 20, 30,40,1,23,56,1]
dict(zip(country,deaths))

{'India': 30, 'UK': 40, 'China': 1, 'USA': 23}

In [7]:
Dict = {} # Empty Dict
for c,d in zip(country,deaths):
    if c not in Dict:
        Dict[c] = d
    else:
        Dict[c] += d 
Dict

{'India': 40, 'UK': 60, 'China': 58, 'USA': 23}

In [12]:
{c: d for c,d in zip(country,deaths) }

{'India': 30, 'UK': 40, 'China': 1, 'USA': 23}

In [9]:
set(['India', 'UK', "India","UK","china","USA","China","China","INDIA","RUSSIA","United Kingdom"])

{'China', 'INDIA', 'India', 'RUSSIA', 'UK', 'USA', 'United Kingdom', 'china'}

In [10]:
lst = list(range(10))
lst

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [24]:
# Can you write a program to find the average of odd numbers in the given list?

oddlist = list(filter(lambda x: x % 2 != 0, lst))
sum(oddlist) // len(oddlist)

5

In [28]:
# Write a Python Program to Find the third Largest Number in the given list?
lst.sort()
lst[-2]

8

In [38]:
# Write a Python Program to find the count of Even and odd numbers in the given list?
lst = [1,23,34,66,6]
len([num  for num in lst if num % 2 == 0]), len([num  for num in lst if num % 2 != 0])

(3, 2)

In [39]:
# Write a Python Program to find the sum of all Even and odd numbers in the given list?
sum([num  for num in lst if num % 2 == 0]), sum([num  for num in lst if num % 2 != 0]) 

(106, 24)

In [42]:
# Write a Python Program to find the Avg. of numbers which are multiples of 7 in the given list? 
Data = [68, 71, 21, 68, 32, 80, 64, 52, 92, 97, 93, 37, 61, 62, 23, 81, 67, 84, 33, 41, 92, 51, 71, 52, 92, 43, 80, 74, 69, 92, 79, 78, 70, 31, 34, 79, 73, 77, 96, 87, 53, 47, 85, 58, 58, 87, 44, 29, 94, 23, 65, 49, 71, 57, 96, 74, 30, 65, 62, 85, 34, 21, 81, 79, 84, 87, 22, 45, 59, 91, 26, 22, 46, 71, 60, 21, 67, 21, 56, 38, 82, 95, 77, 55, 37,61, 59, 89, 61, 75, 97, 72, 58, 23, 78, 20, 95, 67, 59, 56, 93, 82,35, 78, 94, 67, 25, 95, 90, 80, 78, 73, 91, 52, 59, 96, 46, 94, 99,78, 53, 40, 67, 76, 73, 46, 77, 40, 34, 38, 34, 42, 69, 86, 61, 76,21, 90, 52, 65, 36, 93, 55, 86, 95, 65, 30, 89, 86, 20, 92, 46, 58,75, 43, 57, 53, 42, 43, 37, 26, 90, 58, 31, 73, 71, 63, 70, 72, 78,26, 39, 35, 58, 84, 56, 24, 73, 36, 75, 32, 35, 56, 87, 87, 73, 80,78, 25, 61, 38, 94, 36, 90, 70, 65, 34, 61, 44, 85, 41, 50, 23, 34,20, 87, 84, 30, 21, 84, 65, 85, 88, 73, 54, 47, 77, 41, 35, 71]

seven = [num for num in Data if num % 7 == 0]
sum(seven)/ len(seven)

56.4375

In [4]:
def odd_even(number):
    if number <= 0:
        raise ValueError('Number must be positive')
    
    if number % 2 == 0:
        print("Number is even")
    else:
        print("Number is odd")
        
try:
    num= int(input('Enter a number: '))
    odd_even(num)

except ValueError:
    print("Only positive integer are allowed")
except:
    print("Something is wrong")  
    

Only positive integer are allowed


In [6]:
class EMP:
    "A class representing Employee"
    
    def __init__(self,n,a):
        self.full_name = n
        self.age = a
    
    def get_age(self):
        return self.age
        

In [11]:
f = EMP("Boston",23)

In [12]:
getattr(f,"full_name")

'Boston'

In [6]:
class Sample:
    x = 3 # class Variable
    def increment(self):
        self.__class__.x += 1

a = Sample()
a.increment() 

In [2]:
a.__class__.x

4

In [3]:
b = Sample()

In [4]:
b.increment()

In [5]:
a.__class__.x

5

In [7]:
import numpy as np

In [9]:
a = np.arange(10000)
%timeit a + 1

6.14 µs ± 64.6 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [2]:
import numpy as np 
import pandas as pd 


In [1]:
%lsmagic # all magic method

Available line magics:
%alias  %alias_magic  %autoawait  %autocall  %automagic  %autosave  %bookmark  %cd  %clear  %cls  %colors  %conda  %config  %connect_info  %copy  %ddir  %debug  %dhist  %dirs  %doctest_mode  %echo  %ed  %edit  %env  %gui  %hist  %history  %killbgscripts  %ldir  %less  %load  %load_ext  %loadpy  %logoff  %logon  %logstart  %logstate  %logstop  %ls  %lsmagic  %macro  %magic  %matplotlib  %mkdir  %more  %notebook  %page  %pastebin  %pdb  %pdef  %pdoc  %pfile  %pinfo  %pinfo2  %pip  %popd  %pprint  %precision  %prun  %psearch  %psource  %pushd  %pwd  %pycat  %pylab  %qtconsole  %quickref  %recall  %rehashx  %reload_ext  %ren  %rep  %rerun  %reset  %reset_selective  %rmdir  %run  %save  %sc  %set_env  %store  %sx  %system  %tb  %time  %timeit  %unalias  %unload_ext  %who  %who_ls  %whos  %xdel  %xmode

Available cell magics:
%%!  %%HTML  %%SVG  %%bash  %%capture  %%cmd  %%debug  %%file  %%html  %%javascript  %%js  %%latex  %%markdown  %%perl  %%prun  %%pypy  %%python 

In [3]:
%%writefile test.py # magic method for write in python file
array = np.array([1,2,3,4,5,6,7,8,9,dtype = np.float])

Overwriting test.py


In [5]:
!dir

 Volume in drive C is OS
 Volume Serial Number is 30C2-ABAE

 Directory of c:\Github\BOSTON-AI

12/15/2021  11:26 PM    <DIR>          .
12/07/2021  10:02 AM    <DIR>          ..
12/15/2021  11:35 PM             5,616 Assignment.ipynb
12/21/2021  10:27 AM            22,770 DAY01.ipynb
12/21/2021  10:24 AM                56 test.py
12/14/2021  11:55 AM    <DIR>          __pycache__
               3 File(s)         28,442 bytes
               3 Dir(s)  349,691,330,560 bytes free


In [6]:
np.random.randint(5,100,(3,3))

array([[93, 70, 40],
       [15, 28, 58],
       [30, 42, 86]])

In [8]:
np.lcm(7,767)

5369

In [9]:
np.repeat([[1,3],[5,6]],2)

array([1, 1, 3, 3, 5, 5, 6, 6])

In [13]:
np.repeat([[1,3],[5,6]],2,axis=1)

array([[1, 1, 3, 3],
       [5, 5, 6, 6]])

In [17]:
Data = pd.read_csv(r'client.csv',sep=';')

In [18]:
Data.head()

client_id  birth_number  district_id
0          1        706213           18
1          2        450204            1
2          3        406009            1
3          4        561201            5
4          5        605703            5

In [19]:
Data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5369 entries, 0 to 5368
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   client_id     5369 non-null   int64
 1   birth_number  5369 non-null   int64
 2   district_id   5369 non-null   int64
dtypes: int64(3)
memory usage: 126.0 KB


In [21]:
Data.set_index('client_id').head()

birth_number  district_id
client_id                           
1                706213           18
2                450204            1
3                406009            1
4                561201            5
5                605703            5

In [29]:
Data.loc[1]

client_id            2
birth_number    450204
district_id          1
Name: 1, dtype: int64

In [31]:
Data['client_id'].replace({1001:10010,1002:10020}).head()

0    1
1    2
2    3
3    4
4    5
Name: client_id, dtype: int64

In [37]:
Data['birth_number'] = Data['birth_number'].astype(str)


SyntaxError: invalid syntax (<ipython-input-37-f87b1cf55bf5>, line 2)

In [47]:
Data['birth_number'].str[2:4].apply(lambda x: int(x) - 50 if int(x) > 50 else  int(x))

0       12
1        2
2       10
3       12
4        7
        ..
5364    10
5365     4
5366     4
5367    10
5368     8
Name: birth_number, Length: 5369, dtype: int64